version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=DevTools
      - Jwt__Audience=DevToolsUsers
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - applicationUrl=http://localhost:5000
      - Redis__ConnectionString=${REDIS_CONNECTION}
      - Redis__InstanceName=DevTools
      - EmailSettings__SmtpHost=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__EnableSsl=true
      - EmailSettings__Username=${EMAIL_USERNAME}
      - EmailSettings__Password=${EMAIL_PASSWORD}
      - EmailSettings__FromEmail=nhminh22@clc.fitus.edu.vn
      - EmailSettings__FromName=DevTools Support
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=devtools_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: